// @flow

/**
 * A placement generated by the Attivio Business Center
 * that you can display along with search results.
 */
export default class SearchPlacement {
  constructor(
    label: string | null = null,
    imageUrl: string | null = null,
    linkText: string | null = null,
    linkUrl: string | null = null,
    markup: string | null = null,
  ) {
    this.label = label;
    this.imageUrl = imageUrl;
    this.linkText = linkText;
    this.linkUrl = linkUrl;
    this.markup = markup;
  }

  static fromJson(json: any): SearchPlacement {
    const result = new SearchPlacement();
    result.label = json.label;
    result.imageUrl = json.imageUrl;
    result.linkText = json.linkText;
    result.linkUrl = json.linkUrl;
    result.markup = json.markup;
    return result;
  }

  /** The label to display */
  label: string | null;
  /** The URL of an image to display */
  imageUrl: string | null;
  /** The text to display for a hyperlink */
  linkText: string | null;
  /** The URL that should be the target of the hyperlink */
  linkUrl: string | null;
  /** HTML markup for the placement to be displayed as-is */
  markup: string | null;
}
